name: Update resourcepack

on:
 push:
  paths:
   - assets/**
   - pack.mcmeta

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: pull latest and remove old file from repo
        run: |
          git config --global user.name "Mhaks02"
          git config --global user.email "max334201@gmail.com"
          git config pull.rebase false
          git pull
          rm -f release.zip
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'BDSMCustomModels.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
        
      - name: push changes to remote
        run: |
          git add -A
          git commit -m "new pack"
          git push --force

 update-sha1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate SHA1 hash
        id: sha1
        run: |
         sha1=$(openssl dgst -sha1 https://github.com/Mhaks02/BDSMCustomModels/blob/main/BDSMCustomModels.zip?raw=true | awk '{print $2}')
         echo "::set-output name=sha1::$sha1"

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: python .github/workflows/send_sha1.py ${{ steps.sha1.outputs.sha1 }}
